exclude: bindsnet
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
    -   id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
    -   id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]
        files: '^masters/|tests/'
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
